Feat/create add game page
idiglove/oku-no-kumo-fe pull request #15
Opened 2023-04-07 16:57 UTC by enricodelarosa

## Summary of changes

## Change Type
*Put an `x` in all the boxes that apply
- [] Bugfix (non-breaking change which fixes an issue)
- [] Feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Linear issue link

## Wiki link related to this ticket

## Before & after screenshots or video recordings (Before & After)

2023-04-07 17:08 UTC, idiglove reviewed
this looks like PR #11  too?

2023-04-07 17:54 UTC, enricodelarosa commented
> this looks like PR #11 too?



> this looks like PR #11 too?

Yes, but with 2 more commits :)

2023-04-09 22:09 UTC, idiglove requested changes

2023-04-09 22:09 UTC, idiglove commented on project_app/pages/addgame.tsx
> +        }) */
remove comments pls

2023-04-09 22:09 UTC, idiglove commented on project_app/pages/addgame.tsx
> +`;
put this in a separate file thanks

2023-06-30 02:25 UTC, closed without merging