[FEAT -OKU-32]Homepage fixes
idiglove/oku-no-kumo-fe pull request #18
Opened 2023-05-23 21:18 UTC by twentymurial33

## Summary of changes

## Change Type
*Put an `x` in all the boxes that apply
- [] Bugfix (non-breaking change which fixes an issue)
- [] Feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)
Search icon on search bar is misaligned

- Reviews cards should be on top of the snake & ladder board
- Remove the white space between Reviews and Footer
- SVGs are rendering quite blurry
- Water SVG doesn't look right
- Make some unit tests

## Linear issue link
https://linear.app/oku-no-kumo/issue/OKU-32/homepage-fixes

## Wiki link related to this ticket

## Before & after screenshots or video recordings (Before & After)

2023-05-30 03:55 UTC, idiglove requested changes
some comments and questions also suggestions in discord

2023-05-30 03:55 UTC, idiglove commented on project_app/babel.config.js
> +      plugins: ['@babel/plugin-transform-runtime']
what is this for?

2023-05-30 03:55 UTC, idiglove commented on project_app/next.config.js
> +    unoptimized: true
why do we have this?

2023-06-01 13:34 UTC, twentymurial33 commented on project_app/next.config.js
> +    unoptimized: true
Removed

2023-06-01 18:52 UTC, idiglove requested changes

2023-06-01 18:52 UTC, idiglove commented on project_app/components/CardBox.js
> +        </svg>
have this as a separate component

2023-06-01 18:52 UTC, idiglove commented on project_app/components/CardBox.js
> +        </svg>
same here

2023-06-04 22:29 UTC, twentymurial33 commented on project_app/components/CardBox.js
> +        </svg>
In a separate file

2023-06-04 22:29 UTC, twentymurial33 commented on project_app/components/CardBox.js
> +        </svg>
Separated

2023-06-04 22:34 UTC, idiglove commented on project_app/components/RightContainer.js
> +    <div>
do we need the parent div?

2023-06-04 23:05 UTC, twentymurial33 commented on project_app/components/RightContainer.js
> +    <div>
No we don't removed the outer divs

2023-06-04 23:33 UTC, idiglove approved these changes

2023-06-04 23:33 UTC, merged